"""Editorial source for the approved first ten everyday-life books (no AI API calls)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STYLE = "Use case: illustration-story. Premium polished 3D animated-film children's picture-book illustration, matching the existing city vehicle series, rounded human cartoon characters, soft clay-like materials, warm realistic urban home environments, expressive faces, cinematic light, square 1:1 composition. One coherent scene, no collage."
CHARACTERS = "安安 (An'an): six-year-old Chinese girl, round face, ear-length straight black bob, yellow star hairclip on her left, teal hoodie, blue jeans, white sneakers with red trim. Mom: shoulder-length black hair, coral cardigan, cream trousers. Dad: short black hair, navy sweater, beige trousers. Grandma: short silver bob, lavender cardigan. Friend Lele: six-year-old Chinese boy, short black hair, mustard sweatshirt, navy trousers. Keep each person's identity, hair, clothing and proportions consistent. Include only people specified in this page's scene."
NEGATIVE = "No text, letters, captions, speech bubbles, labels, numbers, logos, watermark, anthropomorphic animals, animal families, distorted hands, duplicate characters, scary imagery. Never show anyone eating rotten or moldy food."

BOOKS = [
  ("lan-ping-guo", "烂苹果", "好苹果，要留到哪一天", "珍惜好东西，也要及时享用，别让每一天都变成将就。", "Enjoy good things in good time instead of always saving them for later.", ["珍惜当下", "分享", "生活智慧"], [
    ("周日，妈妈买回一篮苹果。安安挑出一个红亮亮的，闻了闻：“这个一定很甜！”", "On Sunday, Mom brought home a basket of apples. An'an picked a shiny red one and sniffed it. “This one must be sweet!”", "Wide sunny kitchen establishing shot: Mom sets a wicker basket of fresh red apples on an oak table; An'an holds one shiny red apple near her nose with delight. Pale green cabinets, cream curtains."),
    ("妈妈把它放回篮子：“先把这几个不新鲜的处理掉，好的留着明天吃。”安安点点头，把红苹果放在最上面。", "Mom put it back. “Let's deal with the less fresh ones first and save the good ones for tomorrow.” An'an nodded and placed the red apple on top.", "Medium tabletop view in the same kitchen: Mom sorts a few wrinkled apples from the fresh ones; An'an carefully places her shiny apple on top. Nobody eats; a separate discard bowl sits nearby."),
    ("第二天，篮里又有苹果变坏了。妈妈叹口气：“唉，今天又得先处理这些。”那颗红苹果还是留了下来。", "The next day, more apples had gone bad. Mom sighed. “We have these to deal with again.” The shiny red apple stayed in the basket.", "Close view the following morning: several apples have clearly brown spoiled patches, separated into a discard bowl by Mom; the shiny red apple remains in the wicker basket, An'an watches with a puzzled brow. No knife or eating."),
    ("一天，又一天。安安盼着的红苹果也皱了皮。她问：“我们每天都在挑烂苹果，那什么时候才能吃到好的呢？”", "Day after day passed. The red apple An'an had hoped for grew wrinkled too. “We keep picking out bad apples,” she asked. “When do we get to enjoy the good ones?”", "Eye-level emotional close scene: An'an points gently to her now wrinkled red apple in the basket and asks Mom with earnest expression. Mom pauses, thoughtful. No one eats any spoiled apple."),
    ("妈妈看了看篮子，蹲下来：“我总怕浪费，想把好的留住，结果反而让它们放坏了。”安安轻轻拉住她的手。", "Mom looked at the basket and knelt beside her. “I was afraid of wasting them, so I saved the good ones. But that let them go bad.” An'an held her hand.", "Intimate medium shot in the same kitchen: Mom kneels to meet An'an's eyes, both thoughtful and affectionate, child holds her hand; wicker basket visible behind them without dominating frame."),
    ("她们把腐烂的苹果丢掉，检查剩下的新鲜苹果。妈妈洗好一个，切开给安安。咔嚓！这次，安安终于尝到了甜甜的苹果。", "They threw away the rotten apples and checked the fresh ones. Mom washed a good apple and sliced it for An'an. Crunch! At last, An'an tasted a sweet apple.", "Bright close tabletop scene: An'an happily bites a visibly pristine fresh apple slice while Mom offers a clean plate of fresh slices. Spoiled fruit is already disposed of and entirely absent; no knife within child's reach."),
    ("还有几个新鲜的，安安送给了隔壁的乐乐。妈妈把剩下的放进冰箱：“下次少买一点，也能吃得刚刚好。”", "An'an shared a few fresh apples with Lele next door. Mom put the rest in the fridge. “Next time we'll buy fewer, just enough to enjoy.”", "Safe apartment doorway scene: An'an hands Lele a small paper bag with two shiny fresh apples, Mom accompanies her smiling; welcoming urban corridor, no labels."),
    ("晚饭后，桌上是一小盘新鲜苹果。安安笑着说：“今天的好苹果，今天就很好吃。”妈妈也拿起一片，和她一起咬了一口。", "After dinner, a small plate of fresh apples sat on the table. An'an smiled. “Today's good apples taste good today.” Mom took a slice, and they enjoyed them together.", "Warm evening closing shot at the same oak dining table: An'an and Mom share a small plate of pristine apple slices, smiling at each other, cozy lamp and city windows, basket nearly empty."),
  ], "及时享用与合理保存，理解节省和将就的区别。", "不要用浪费羞辱孩子；腐烂、发霉的苹果丢弃，不以削掉坏处作为食用示范。", ["妈妈为什么一直把好苹果留下？", "有什么喜欢的东西，我们可以在今天好好使用？"], "一起检查家里的水果，由成人判断新鲜程度，选一份新鲜水果分享，商量下次适量购买。"),
  ("she-bu-de-chuan-de-xin-xie", "舍不得穿的新鞋", "鞋盒里的春天", "喜欢的东西，在合适的时候使用，才能陪我们走过生活。", "Use the things you love at the right time so they can be part of your life.", ["珍惜当下", "成长", "物品使用"], [
    ("安安有了一双新鞋：白鞋面，红鞋边，走起路来轻轻的。她在镜子前转了一圈，又小心地放回鞋盒。", "An'an got new shoes with white tops and red trim. They felt light on her feet. She turned in front of the mirror, then carefully put them back in the box.", "An'an in her home entryway admiring new white sneakers with red trim in a low mirror, open plain shoebox nearby. Mom beside her, delighted. The new pair is the only pair worn."),
    ("晴天，妈妈说：“穿新鞋去公园吧。”安安摇头：“沙子会把它们弄脏的。”她穿上旧鞋，出了门。", "On a sunny day, Mom said, “Wear your new shoes to the park.” An'an shook her head. “The sand might get them dirty.” She went out in her old shoes.", "Home entryway medium shot: An'an closes the plain shoebox containing pristine white-red shoes and instead wears clearly faded gray old sneakers, Mom holds a park tote by door."),
    ("雨天，窗上挂着小水珠。“今天更不能穿啦！”安安摸摸鞋盒，觉得里面的新鞋像一件宝贝。", "Raindrops covered the window. “I definitely can't wear them today!” An'an touched the box. The shoes inside felt like treasure.", "Cozy rainy-day bedroom: An'an in socks crouches beside a closed shoebox, stroking lid, rain beads on window. Quiet reflective mood; no shoes on feet."),
    ("春天过去，夏天来了。安安长高了一点。学校要去郊游，她终于把新鞋拿出来：“这次一定穿！”", "Spring passed, and summer arrived. An'an had grown a little taller. Her class was going on an outing. She finally opened the box. “This time I'll wear them!”", "Sunny home entryway months later: An'an opens same shoebox excitedly, Mom holds a small orange backpack for a school outing, green summer trees outside. New shoes still white with red trim."),
    ("可是，脚尖挤在一起，怎么也不舒服。安安低下头：“它们一次都没陪我出门，就小了。”", "But her toes felt squeezed, and the shoes were uncomfortable. An'an looked down. “They got too small before we even went out together.”", "Low intimate shot: An'an sits on entry bench trying on the now too-small new shoes, toes pressing subtly at fronts, disappointed expression; Mom sits beside her listening. No exaggerated deformity."),
    ("妈妈抱抱她：“你长大了，鞋子没有长大。珍惜它，也可以是穿着它走路，再把它擦干净。”", "Mom hugged her. “You grew, but the shoes didn't. Taking care of them can mean wearing them, then cleaning them afterward.”", "Tender eye-level entryway shot: Mom embraces seated An'an, plain shoebox and removed white-red sneakers at their feet, a soft cleaning cloth on bench."),
    ("安安和妈妈把新鞋送给了正好穿得下的表妹。表妹穿着它，在屋里轻轻走了两圈，笑得像一朵花。", "An'an and Mom gave the shoes to her younger cousin, whose feet fit just right. Her cousin walked around the room, beaming.", "Living room: younger Chinese cousin with black pigtails and pink dress wears donated white-red sneakers, walking delightedly; An'an in gray old sneakers and Mom watch smiling. Only cousin wears new pair."),
    ("郊游那天，安安穿着合脚的鞋，跑过草地。回家后，她擦掉鞋边的泥：“今天，你陪我去了好多地方。”", "On the outing, An'an wore shoes that fit and ran across the grass. Back home, she wiped off the mud. “You came to so many places with me today.”", "Closing home entryway scene: An'an seated in socks gently wipes small mud marks from her comfortably fitting gray sneakers with a cloth, orange outing backpack nearby, sunset window."),
  ], "用实际使用和照顾，代替过度保护物品。", "尊重孩子爱惜新物品的心情，不催促消费；不合脚的鞋及时更换或转赠。", ["安安在担心什么？", "东西用过以后，我们怎样照顾它？"], "选一件舍不得使用的小物品，安排一次合适的使用，再一起清洁和收好。"),
  ("te-bie-de-ri-zi-shi-na-tian", "特别的日子是哪天", "一个普通下午的礼物", "愿意用心的今天，也可以成为特别的一天。", "An ordinary day can become special when we give it care.", ["珍惜当下", "创造", "家人陪伴"], [
    ("安安有一盒漂亮贴纸：星星、花朵，还有一颗小太阳。她打开看一看，又合上：“要留给特别的日子。”", "An'an had a box of lovely stickers: stars, flowers, and a little sun. She peeked inside and closed it. “I'll save them for a special day.”", "Bedroom desk close scene: An'an examines a box of colorful star, flower and sun stickers, blank sheets nearby, then protects them carefully. No text on stickers."),
    ("星期一很普通，星期二也很普通。安安每天都问：“特别的日子，怎么还没来呀？”", "Monday felt ordinary, and so did Tuesday. Each day, An'an wondered, “Why hasn't the special day come yet?”", "Quiet window scene: An'an sits at her desk gazing out at everyday city courtyard, unopened sticker box in foreground, softly expectant expression. No calendar text."),
    ("星期三下午，奶奶来做客。她带来一小袋橘子，笑着说：“今天想来看看你。”", "On Wednesday afternoon, Grandma visited with a small bag of oranges. “I wanted to see you today,” she said with a smile.", "Apartment doorway: Grandma with silver bob and lavender cardigan carries oranges in a cloth bag; An'an greets her joyfully, Mom welcomes them from entryway."),
    ("安安想送奶奶一张卡片。她拿出白纸，又停在贴纸盒前：“可是，今天只是星期三。”", "An'an wanted to make Grandma a card. She took out some paper, then paused at the sticker box. “But it's only Wednesday.”", "Desk medium shot: An'an holds a blank folded paper and looks hesitantly at sticker box, Mom sits beside desk gently listening, no writing."),
    ("妈妈问：“你现在想让奶奶开心吗？”安安点头。妈妈笑了：“那今天就有一件特别的事了。”", "Mom asked, “Would you like to make Grandma happy today?” An'an nodded. Mom smiled. “Then today already has something special in it.”", "Close warm conversation at desk: Mom meets An'an's eyes, child brightens with realization, blank folded card and sticker box between them."),
    ("安安贴上一颗星星，又贴一朵花。小太阳贴歪了，她笑起来：“像奶奶笑着歪了歪头。”", "An'an added a star and a flower. The little sun went on crooked. She laughed. “It looks like Grandma tilting her head when she smiles.”", "Overhead detailed crafting view: child's hands place sun slightly tilted alongside one star and one flower on blank folded card, An'an's happy face at frame edge, Mom nearby. No writing or scissors."),
    ("奶奶把卡片捧在手里：“这张卡片，是今天才有的呀。”她把安安抱进怀里，橘子的香味轻轻飘过来。", "Grandma held the card. “This card could only happen today.” She hugged An'an, and the sweet smell of oranges drifted around them.", "Living room close emotional scene: Grandma hugs An'an while holding handcrafted card with star flower crooked sun, plain plate of peeled oranges on low table, Mom smiles in background."),
    ("晚上，安安又打开贴纸盒。她没有等节日，而是给明天要看的书贴上一朵花。原来，普通的日子也可以亮起来。", "That evening, An'an opened the sticker box again. Without waiting for a holiday, she put a flower on the notebook she would use tomorrow. Ordinary days could shine too.", "Peaceful bedroom closing scene: An'an places a flower sticker on cover of her own blank notebook under a warm desk lamp, sticker box open, night city window. No lettering."),
  ], "主动创造日常仪式，表达心意。", "贴纸等个人物品由孩子决定使用；不以送礼作为表达爱的唯一方式。", ["星期三为什么变特别了？", "不用买东西，我们可以做什么让今天值得记住？"], "一起为今天留下一张画、一段话或一个拥抱，由孩子选择表达方式。"),
  ("wan-ju-shan-li-zhao-xiao-che", "玩具山里找小车", "给快乐留一条小路", "给物品留好位置，也给喜欢的事情留出空间。", "Give things a place, and leave space for the things you enjoy.", ["整理", "物品使用", "自主选择"], [
    ("安安想铺一条小公路，让红色小车从沙发开到窗边。可是，小车不见了。她翻开一只盒子，又翻开另一只。", "An'an wanted to build a little road for her red toy car, from the sofa to the window. But the car was missing. She searched one box, then another.", "Wide urban living room: An'an searches two overflowing toy bins beside sofa, clear floor route to window blocked by toys; treasured small red car absent from view."),
    ("机器人、积木、拼图，一件压着一件。安安越找越急：“我有这么多玩具，怎么连最喜欢的都找不到？”", "Robots, blocks, and puzzles piled on top of one another. An'an grew frustrated. “I have so many toys. Why can't I find my favorite?”", "Low floor-level close shot: An'an surrounded by scattered colorful toy robot blocks and puzzles, puzzled frustrated face, no toy car visible. Keep believable uncluttered focal composition."),
    ("爸爸走过来，没有马上替她收拾：“我们先找出你最近最想玩的，好不好？”安安把常玩的积木放到一边。", "Dad came over without taking over. “Shall we start with the things you most want to play with?” An'an put her favorite blocks aside.", "Dad in navy sweater kneels beside An'an, child chooses favorite wooden blocks into a small open basket, calm cooperative living room scene."),
    ("有些玩具她已经很久没碰了，有些还想留下。爸爸说：“你来决定，我们慢慢分。”安安给它们找了不同的盒子。", "Some toys had not been touched for a long time. Others she wanted to keep. “You decide,” Dad said. “We'll sort them slowly.” An'an chose different boxes.", "Overhead sorting scene: An'an and Dad arrange three plain open boxes with distinct favorite toys, stored toys and optional giveaway toys, no labels, child clearly directs choices."),
    ("在一堆布偶下面，一点红色露了出来。“找到啦！”安安举起小车，车轮上还缠着一根毛线。", "A flash of red appeared beneath some soft toys. “Found it!” An'an lifted her car. A piece of yarn was caught around a wheel.", "Close joyful discovery: An'an lifts small red toy car from underneath ordinary inanimate plush toys, tiny loose yarn at one wheel, Dad smiles nearby. Plush toys remain toys, not animal people."),
    ("爸爸帮她取下毛线。安安给小车留了一个容易拿到的位置，又空出一块地板：“这里就是我的公路。”", "Dad removed the yarn. An'an gave the car an easy-to-reach home and cleared a patch of floor. “This is my road.”", "Side living room view: Dad gently untangles yarn from red car while An'an clears a strip of floor, low open shelf with car-sized parking space visible."),
    ("她决定把几件完好的玩具送给需要的小朋友。剩下的各有位置，拿出来容易，放回去也容易。", "She chose a few good toys to give to other children who needed them. The rest had their own places, easy to take out and put away.", "An'an willingly places a good toy robot into plain donation bag while Dad holds it, orderly toy baskets and low shelf behind, no recipient invented, no writing."),
    ("红色小车终于开到了窗边。安安趴在地上，搭起一座小桥。房间里的玩具少了一点，她玩的时间却长了好多。", "At last, the red car reached the window. An'an lay on the floor and built a little bridge. There were fewer toys in the room, but more room to play.", "Warm wide closing living room shot: An'an builds wooden block bridge on a clear floor road from sofa toward window, small red car underneath bridge, Dad relaxed nearby, organized baskets."),
  ], "让孩子参与整理和物品取舍，建立易取易放的位置。", "不擅自丢弃或赠送孩子的东西；数量多少不是衡量整洁或快乐的标准。", ["小车为什么难找？", "你最常玩的东西，放在哪里最方便？"], "由孩子选择一个小区域整理，给常用物品安排容易拿到的位置。"),
  ("zai-wan-wu-fen-zhong", "再玩五分钟", "最后一局，也要留出时间", "照顾自己的兴致，也认真照顾与别人的约定。", "Make room for your own fun and for the promises you make to others.", ["时间安排", "约定", "朋友"], [
    ("下午三点，安安约好和乐乐在小区公园玩。出门前，她还想把桌上的积木房子搭完。", "An'an had agreed to meet Lele in the neighborhood park at three. Before leaving, she wanted to finish the block house on her table.", "Home play table: An'an builds wooden block house, orange backpack ready by door, Mom nearby, afternoon sunshine. No readable clock or numbers."),
    ("妈妈提醒：“我们该准备了。”安安说：“再玩五分钟！”房子还缺一个屋顶，她又找来一块积木。", "Mom said, “It's time to get ready.” “Five more minutes!” An'an replied. The house still needed a roof, so she searched for another block.", "Medium scene: Mom points gently toward prepared shoes at door, An'an concentrates on unfinished block roof and reaches for one more block, no screens."),
    ("屋顶搭好了，她又想添一个花园。等安安终于穿好鞋，公园里的影子已经长了。", "The roof was finished, but then she wanted a garden. By the time An'an had her shoes on, the shadows in the park had grown long.", "Late afternoon entryway: An'an hastily but safely puts on white-red sneakers while Mom waits calmly, elaborate block house visible deeper inside, long sun shadows."),
    ("乐乐已经跟爸爸回家了。安安站在空空的滑梯旁，轻声说：“我还以为，一小会儿不会有关系。”", "Lele had already gone home with his dad. Beside the empty slide, An'an whispered, “I thought a little longer wouldn't matter.”", "Quiet neighborhood park: An'an stands beside empty slide holding Mom's hand, disappointed, sunset warm long shadows, no friend present."),
    ("妈妈坐到她身边：“你很想搭完房子，我知道。乐乐也在等你。准备出门，同样需要时间。”", "Mom sat beside her. “I know you wanted to finish your house. Lele was waiting too. Getting ready takes time as well.”", "Park bench close scene: Mom and An'an sit side by side at child's eye level, listening empathetically, empty slide softly blurred behind."),
    ("回家后，安安请妈妈帮忙联系乐乐。她说：“今天让你等了，对不起。下次我会早点准备。”", "At home, An'an asked Mom to help her contact Lele. “I'm sorry I kept you waiting today. Next time I'll get ready earlier.”", "Living room: Mom holds a plain phone on speaker with blank unlit screen, An'an speaks earnestly beside her, block house on table. No visible interface text."),
    ("第二次约好时，安安先和妈妈商量：积木玩到沙漏漏完，拍张照片，明天接着搭，再留时间穿鞋、拿水壶。", "For their next meeting, An'an and Mom made a plan: stop when the sand timer finished, take a photo, continue tomorrow, and leave time for shoes and a water bottle.", "Play table side view: An'an and Mom set a small sand timer next to unfinished wooden block house, plain water bottle and orange backpack ready, warm cooperative mood."),
    ("沙漏空了，安安有点舍不得，还是站起身。公园里，乐乐向她挥手。她笑着跑过去：“今天，我们有好多时间一起玩！”", "When the timer emptied, An'an wished she could keep building, but she stood up. In the park, Lele waved. She smiled. “Today we have plenty of time to play together!”", "Bright afternoon closing park scene: An'an joins Lele near safe grassy play area, both excited, Mom and Lele's dad nearby supervising, playful meeting before sunset."),
  ], "共同安排过渡时间，练习遵守约定和补救。", "不把难以停下游戏说成故意不听话；用预告、保留作品和成人协助帮助转换。", ["除了玩五分钟，出门还需要做哪些事？", "有什么办法让没玩完的东西等我们回来？"], "一起安排下一次出门前的结束提醒，给收尾和准备留出时间。"),
  ("wo-de-bing-gan-zen-me-geng-xiao", "我的饼干怎么更小", "小熊耳朵的秘密", "看见自己拥有的快乐，也可以说出自己的需要。", "Notice what you enjoy, and feel free to speak about what you need.", ["比较", "感受", "分享"], [
    ("点心时间，安安和乐乐各拿到一块饼干。乐乐的是圆圆的大饼干，安安的是一只小熊。", "At snack time, An'an and Lele each got a cookie. Lele's was large and round. An'an's was shaped like a little bear.", "Bright kitchen snack table: Mom places separate plates before An'an and Lele, child has small bear-shaped cookie, boy larger round cookie, equal cups of water, cookies clearly distinct."),
    ("安安看看自己的，又看看乐乐的：“为什么我的更小？”她把盘子往前推了一点，心里不太开心。", "An'an looked from her cookie to Lele's. “Why is mine smaller?” She pushed her plate away a little and felt unhappy.", "Close table view: An'an looks wistfully at Lele's large round cookie while pushing her own bear-cookie plate slightly away, Lele unaware, Mom listens nearby."),
    ("妈妈说：“你也想要大一点的，对吗？可以告诉我。”安安点点头，眼睛还是追着乐乐的饼干。", "Mom said, “You'd like a bigger one too, right? You can tell me.” An'an nodded, still watching Lele's cookie.", "Mom kneels beside seated An'an at snack table, acknowledges child's feeling warmly, both distinct cookies still intact on their plates, no moralizing gesture."),
    ("乐乐忽然凑过来：“你的小熊有耳朵！我的圆饼干都没有。”安安低头，才看见两只小小的圆耳朵。", "Lele leaned closer. “Your bear has ears! My round cookie doesn't.” An'an looked down and noticed its two little round ears.", "Detailed child-eye table shot: Lele points with delight toward bear cookie's two round ears without touching it, An'an notices and begins smiling, plain round cookie on boy's own plate."),
    ("她轻轻咬下一只耳朵。咔嚓，里面还有一点燕麦香。“真的挺好吃。”安安又看了看小熊的脸。", "She took a little bite of one ear. Crunch! It had a gentle oat flavor. “It really is tasty.” An'an looked at the bear's face again.", "Close expressive scene: An'an bites one ear of bear-shaped cookie with pleasure, remaining cookie has one clearly missing ear, Lele sits nearby with round cookie."),
    ("乐乐想尝尝小熊饼干，安安也想尝尝圆饼干。他们商量好，各分出一小块，放进对方的盘子。", "Lele wanted to try the bear cookie, and An'an wanted to try the round one. They agreed to share a small piece with each other.", "Overhead snack tabletop: children use clean hands to place small pieces of their own cookies onto each other's separate plates, bear cookie still recognizable, round cookie with a small piece missing, Mom present."),
    ("安安还没吃饱，便告诉妈妈。妈妈又拿来一些点心：“想吃多少可以商量，不用只盯着别人的盘子。”", "An'an was still hungry and told Mom. Mom brought more snacks. “We can talk about how much you'd like. You don't have to only watch someone else's plate.”", "Warm kitchen medium shot: An'an asks Mom directly, Mom offers a small communal plate of extra plain snacks, Lele content beside her, relaxed noncompetitive atmosphere."),
    ("回家路上，安安记得小熊耳朵的脆，也记得圆饼干的香。原来，吃点心还有比比较大小更有趣的事。", "On the way home, An'an remembered the crunchy bear ear and the tasty round cookie. Snack time had more to offer than comparing sizes.", "Closing neighborhood pedestrian path: An'an walks hand in hand with Mom smiling reflectively, Lele waves from safe doorway, leafy city setting, no literal floating cookie graphics."),
  ], "接纳比较带来的感受，同时练习欣赏和表达需要。", "不要求孩子以知足压下饥饿或公平诉求；分享出于自愿，不比较食量。", ["安安一开始为什么不开心？", "如果还没吃饱，可以怎么说？"], "用两种不同形状的点心观察特点，由孩子决定是否分享，并表达是否吃饱。"),
  ("yi-bei-da-fan-de-niu-nai", "一杯打翻的牛奶", "先说出来，再一起擦干净", "犯错以后，及时说出来、一起补救，事情就能慢慢变好。", "When something goes wrong, speaking up and making repairs can help.", ["诚实", "补救", "情绪"], [
    ("安安正在画一座彩虹桥，手边放着一杯牛奶。她伸手拿蓝色笔，袖子碰到了杯子。", "An'an was drawing a rainbow bridge with a cup of milk nearby. When she reached for a blue crayon, her sleeve bumped the cup.", "Home drawing desk: An'an reaches for blue crayon, teal sleeve touches a plain milk cup beginning to tip, blank abstract rainbow bridge drawing, no text."),
    ("哗！牛奶流过桌面，碰到了画纸边。安安愣住了：“妈妈会不会生气？”", "Splash! Milk ran across the table and reached the edge of her drawing. An'an froze. “Will Mom be angry?”", "Close desk scene immediately after spill: intact plastic cup lies on side, small milk puddle touches edge of rainbow drawing, An'an startled, no broken glass."),
    ("她拿另一张纸盖上去，想把牛奶藏住。纸湿了，下面的书角也湿了。安安越弄越慌。", "She covered the milk with another sheet of paper, hoping to hide it. The paper got wet, and so did the corner of a book underneath. An'an grew more worried.", "Detailed tabletop view: An'an's hands lay a blank paper onto milk puddle, paper visibly soaked, corner of plain book nearby damp, anxious child expression."),
    ("妈妈听见动静，走了过来。安安攥着湿纸，小声说：“是我碰倒的。我想藏起来，可是越弄越糟了。”", "Mom came over when she heard the noise. Holding the wet paper, An'an whispered, “I knocked it over. I tried to hide it, but I made it worse.”", "Medium eye-level desk scene: Mom approaches calmly, An'an holds damp paper and admits spill with worried face, no angry expressions, milk mess contained."),
    ("妈妈先把杯子扶好：“谢谢你告诉我。我们先把干的东西挪开，再拿抹布。”安安呼出一口气。", "Mom stood the cup upright. “Thank you for telling me. Let's move the dry things away and get a cloth.” An'an let out a breath.", "Mom sets intact plastic cup upright while An'an moves dry crayons into a safe tray, cloth in Mom's other hand, cooperative reassuring composition."),
    ("她擦桌子，妈妈擦书角。湿画纸摊开放好，等它慢慢干。那座彩虹桥有一点花了，但还看得见。", "An'an wiped the table while Mom dried the book's corner. They laid the wet drawing flat to dry. The rainbow bridge was a little blurred, but still visible.", "Wide desk cleanup: An'an wipes tabletop with small cloth, Mom carefully blots plain book corner, slightly smudged rainbow drawing laid flat on separate dry tray."),
    ("安安想了想，把牛奶杯移到旁边的小桌上：“这里离画纸远一点。”妈妈点头：“这个办法可以试试。”", "An'an moved her milk to a small side table. “This is farther from my drawing.” Mom nodded. “That's a good idea to try.”", "An'an puts upright plastic milk cup on sturdy side table away from drawing supplies, Mom observes encouragingly, dry main desk ready for painting."),
    ("画纸干了，安安给花掉的地方添了几朵云。她看看妈妈：“下次出了事，我先告诉你。”妈妈说：“我们一起想办法。”", "When the paper dried, An'an added clouds to the blurry parts. “Next time, I'll tell you first,” she said. Mom smiled. “We'll work it out together.”", "Warm close closing shot: An'an adds simple cloud shapes with crayon to dried rainbow drawing, Mom sits beside her, milk cup safely on separate side table, trusting smiles."),
  ], "建立犯错后可以求助和补救的安全感。", "先平静处理，再讨论原因；不要因孩子坦白而追加羞辱或惩罚。", ["安安为什么想把牛奶藏起来？", "我们可以先做哪一步，让事情好一点？"], "用少量清水练习擦拭和移动物品，再一起选一个离画纸远的杯子位置。"),
  ("deng-wo-xin-qing-hao-le-zai-shuo", "等我心情好了再说", "一句有点磕巴的对不起", "重要的话，可以带着紧张说出来，也可以给彼此一点时间。", "You can say something important even while nervous, and give each other time.", ["朋友", "道歉", "情绪"], [
    ("安安和乐乐搭一座桥。乐乐刚摆好一块积木，安安就伸手拿走：“我要放在这里！”乐乐的桥倒了。", "An'an and Lele were building a bridge. Just as Lele placed a block, An'an took it. “I need it here!” His bridge fell.", "Community indoor play table: An'an removes one supporting wooden block, Lele's small block bridge collapses harmlessly on table, both children surprised, no aggression."),
    ("乐乐皱起眉：“你都没有问我。”安安也有点生气，转过身去。两个人各坐在桌子一边。", "Lele frowned. “You didn't ask me.” An'an felt upset too and turned away. They sat on opposite sides of the table.", "Wide playroom: An'an and Lele sit apart at two ends of same low table, fallen bridge blocks between them, hurt expressions, adult visible at a distance."),
    ("回家后，安安想起那座倒掉的桥。她知道自己该道歉，却把话咽回去：“等我心情好了再说吧。”", "At home, An'an thought about the fallen bridge. She knew she should apologize, but swallowed the words. “I'll say it when I feel better.”", "Reflective bedroom scene: An'an sits beside a few wooden blocks looking down with regret, Mom listens from nearby, soft dusk lighting."),
    ("第二天，安安在小区遇见乐乐。她想开口，又低下头。乐乐走远了，她心里更难受了。", "The next day, An'an saw Lele in the neighborhood. She wanted to speak but looked down. As he walked away, she felt worse.", "Safe residential courtyard: An'an stands beside Mom hesitant, Lele walks away with his father along pedestrian path, visible emotional distance, no road traffic."),
    ("妈妈听她说完，问：“你想让乐乐知道什么？”安安说：“我不是不想和他玩。我知道，拿积木前应该问他。”", "After listening, Mom asked, “What would you like Lele to know?” An'an said, “I do want to play with him. I know I should have asked before taking his block.”", "Home sofa intimate conversation: An'an explains with earnest hands, Mom sits beside her attentive, a single wooden block on table as reminder."),
    ("她们一起练了练。安安发现，紧张还在，话却已经能说出来：“对不起，我没问你就拿走了积木。”", "They practiced together. An'an was still nervous, but the words came out. “I'm sorry I took your block without asking.”", "Medium living room: An'an practices apology aloud facing supportive Mom, holds hands together nervously but determined, calm warm light."),
    ("再见面时，安安有点磕巴地说完，又问：“下次我想用你的积木，先问你，好吗？”乐乐想了想：“好。我刚才也需要一点时间。”", "When they met again, An'an stumbled through her apology. “Next time I'll ask before using your blocks. Is that okay?” Lele thought for a moment. “Okay. I needed some time too.”", "Community playroom face-to-face scene: An'an apologizes sincerely to Lele at same block table, boy considers calmly, Mom present unobtrusively, no forced hug."),
    ("他们重新搭桥。安安伸手前先问了一句，乐乐把积木递给她。桥慢慢变长，那句难说的话也没有那么重了。", "They built the bridge again. An'an asked before reaching, and Lele passed her a block. As the bridge grew, the difficult words felt lighter.", "Joyful closing play-table scene: Lele willingly hands An'an a wooden block, both build a longer sturdy bridge together, warm human cartoon expressions, Mom in background."),
  ], "练习具体道歉和行为补救，理解对方可以暂时不接受。", "不强迫立刻道歉或和好；等待是调节情绪的需要时应得到尊重。", ["安安想让乐乐知道什么？", "除了说对不起，她还改变了什么？"], "用玩具演练借用前询问，以及说清具体行为、提出补救的道歉。"),
  ("zen-me-zhi-you-wo-zai-shou-shi", "怎么只有我在收拾", "家里的事，大家一起商量", "看见别人做的事，也让自己的付出被看见。", "Notice what others do, and let your own efforts be seen too.", ["家务", "家庭合作", "公平"], [
    ("周六，安安刚玩完积木，妈妈提醒她收好。她抱着盒子嘟囔：“怎么又是我？家里只有我在收拾吗？”", "On Saturday, Mom reminded An'an to put away her blocks. Holding the box, she grumbled, “Me again? Am I the only one tidying up?”", "Living room: An'an holds an empty block box looking frustrated at scattered blocks, Mom gently asks from nearby, family home weekend light."),
    ("妈妈没有急着反驳：“你觉得累了？那我们先歇一会儿，也看看今天家里有哪些事要做。”", "Mom did not argue. “Are you feeling tired? Let's rest a little and see what needs doing at home today.”", "Sofa close conversation: Mom and An'an sit briefly to rest, block box on floor, mother empathetically acknowledges feeling, no scolding gesture."),
    ("阳台上，爸爸正在晾衣服。他把湿衣服一件件抖开，挂上衣架。安安帮他递了一只衣夹。", "On the balcony, Dad was hanging laundry. He shook out each wet item and hung it up. An'an passed him a clothespin.", "Safe enclosed balcony: Dad hangs laundry on low indoor rack while An'an passes a clothespin, protective closed window panels, child away from height hazards."),
    ("厨房里，奶奶在洗菜，妈妈在擦桌子。还有倒垃圾、买东西、记住明天要带的水壶。原来，有些事不容易被看见。", "In the kitchen, Grandma washed vegetables and Mom wiped the table. There was rubbish to take out, shopping to do, and tomorrow's water bottle to remember. Some jobs were easy to miss.", "Wide kitchen establishing scene: Grandma washes vegetables at sink, Mom wipes dining table, Dad carries small tied trash bag toward door, An'an observes; each person distinct, no montage."),
    ("安安说：“我看见了。可是有时候，我还是觉得自己收得太多。”妈妈点头：“那也可以说，我们一起商量。”", "An'an said, “I see it now. But sometimes I still feel I tidy too much.” Mom nodded. “You can say that too. Let's talk about it together.”", "Family dining table conversation: An'an speaks assertively but calmly, Mom listens attentively, Dad and Grandma seated too, plain paper in center, no guilt or scolding."),
    ("他们把家务画在纸上：积木、衣架、菜篮、抹布。安安选了收自己的玩具和摆餐巾，重的、危险的事交给大人。", "They drew the jobs on paper: blocks, hangers, a vegetable basket, and a cloth. An'an chose her toys and the napkins. Adults kept the heavy and unsafe jobs.", "Overhead family planning table: simple hand-drawn pictograms of blocks hanger vegetable basket and cloth on blank paper, An'an points to toy and napkin pictograms, family hands around paper, no writing."),
    ("下午，大家各做一小会儿。爸爸帮安安托住盒子，她把最后几块积木放进去：“这样容易多了！”", "That afternoon, everyone worked for a little while. Dad steadied An'an's box as she put in the last blocks. “This is much easier!”", "Living room cooperative cleanup: Dad holds light block box steady at child's height while An'an puts final blocks inside, Mom places cushions nearby, teamwork."),
    ("晚上，一家人坐在干净的桌边。安安说：“谢谢你们今天做的事。”奶奶笑着回答：“也谢谢你的小餐巾。”", "That evening, the family sat around the clean table. “Thank you for what you did today,” An'an said. Grandma smiled. “And thank you for the little napkins.”", "Warm evening closing family dining scene: An'an Mom Dad Grandma seated at tidy oak table with neatly laid napkins, affectionate appreciation, ordinary food no text."),
  ], "建立可讨论的家务分工，看见劳动并尊重疲劳。", "不以别人更辛苦否定孩子感受；不按性别分家务，只安排适龄安全任务。", ["有哪些家务平时不容易被看见？", "哪一件事你愿意做，哪一件需要帮忙？"], "画出三四项家务，让家人共同选择分工，过几天再一起调整。"),
  ("bu-tai-wan-mei-de-ye-can", "不太完美的野餐", "屋檐下的三明治", "计划有变化时，照顾失望，再找一种可以享受的方式。", "When plans change, make room for disappointment and look for another way to enjoy the day.", ["适应变化", "家庭陪伴", "情绪"], [
    ("安安盼了一星期的野餐终于到了。她和爸爸装好三明治，妈妈带上毯子。安安想：“今天一定特别棒！”", "The picnic An'an had waited for all week was finally here. She and Dad packed sandwiches, and Mom brought a blanket. “Today will be wonderful!” she thought.", "Sunny home kitchen preparation: An'an and Dad pack sandwiches into plain lunchbox, Mom folds picnic blanket beside basket, orange backpack ready, cheerful anticipation."),
    ("到了公园，刚铺好毯子，雨点就落了下来。安安伸出手：“不是说今天晴天吗？”", "At the park, raindrops fell just as they spread the blanket. An'an held out her hand. “Wasn't it supposed to be sunny?”", "Park lawn: family begins spreading blanket, a few gentle rain droplets appear, An'an looks at open palm puzzled, Mom and Dad gather things promptly; no storm or lightning."),
    ("爸爸和妈妈带她走到附近的亭子里。打开餐盒，三明治还被水壶压扁了。安安的嘴角一点点垂下来。", "Mom and Dad took her to a nearby pavilion. When they opened the lunchbox, the sandwiches had been squashed by the water bottle. An'an's smile faded.", "Dry sheltered open park pavilion: family sits safely at table, opened lunchbox shows clean squashed sandwiches, water bottle beside it, An'an disappointed, soft rain outside."),
    ("“这不是我想要的野餐。”安安抱住膝盖。妈妈坐在她旁边：“你期待了很久，现在失望也很正常。”", "“This isn't the picnic I wanted.” An'an hugged her knees. Mom sat beside her. “You waited a long time. It's okay to feel disappointed.”", "Close pavilion bench scene: An'an seated hugging knees upset, Mom beside her listening softly, Dad keeps picnic things dry, rain blurred in background."),
    ("他们安静地听了一会儿雨。嗒，嗒，屋檐滴下水珠。安安抬起头：“像有人在敲一个小鼓。”", "They listened to the rain for a while. Tap, tap, drops fell from the roof. An'an looked up. “It sounds like someone playing a tiny drum.”", "Atmospheric medium pavilion view: An'an looks toward droplets falling outside roof edge, family seated dry under shelter, soft ripples in outdoor puddle, contemplative wonder."),
    ("爸爸举起扁三明治：“欢迎来到扁扁餐厅。”安安忍不住笑了。她咬了一口：“形状变了，味道还在。”", "Dad held up a squashed sandwich. “Welcome to the Flat Sandwich Café.” An'an couldn't help laughing. She took a bite. “Its shape changed, but it still tastes good.”", "Playful eye-level pavilion table shot: Dad presents a clean flattened sandwich on plate with humorous expression, An'an laughs and tastes another, Mom smiles; food dry and safe."),
    ("妈妈提议编一个雨点故事，安安接着讲。雨小了以后，他们沿着干爽的小路走了一会儿，看叶尖上的水珠。", "Mom began a raindrop story, and An'an added to it. When the rain eased, they took a short walk along a dry path and looked at drops on the leaves.", "Park pedestrian path after light rain: An'an holds Mom's hand observing water droplets on nearby leaf, Dad alongside carrying picnic basket, path safe and not flooded, no storm."),
    ("回家时，安安说：“今天和我想的不一样。不过，扁扁三明治和小鼓雨，我都会记得。”她把野餐毯折好，等下一次出发。", "On the way home, An'an said, “Today wasn't what I expected. But I'll remember the flat sandwiches and the little rain drums.” She folded the blanket, ready for another outing.", "Warm closing home entryway shot: An'an and Mom fold dry picnic blanket together, Dad sets basket down, late afternoon sun returns through city window, happy reflective family."),
  ], "先接纳失望，再共同寻找可行的新安排。", "不强迫孩子立刻乐观；遇到雷暴、积水或其他危险应及时离开。", ["妈妈怎样回应安安的失望？", "计划变了，我们还可以选择哪些事情？"], "为下一次出游一起准备一个室内备选活动，让孩子也参与选择。"),
]

EXTRA_PAGES = {
    "lan-ping-guo": [
        (2, "妈妈把苹果一颗颗排开。安安发现，有的光滑饱满，有的已经皱了皮：“它们能等一样久吗？”", "Mom lined up the apples. Some were smooth and firm; others were wrinkled. “Can they all wait just as long?” An'an asked.", "Overhead kitchen table: Mom and An'an examine a row of pristine and wrinkled apples, curious child touches only a fresh apple, no eating."),
        (3, "安安又指了指最红的那颗：“今天吃它不好吗？”妈妈说：“它看起来还好，先等等吧。”", "An'an pointed to the reddest one again. “Couldn't we eat it today?” Mom replied, “It still looks good. Let's wait a little.”", "Kitchen close conversation: An'an points at shiny red apple atop wicker basket, Mom thoughtfully postpones, a separate discard bowl holds bad fruit, no eating."),
        (4, "安安在篮子旁放了一张自己画的苹果。她想，明天吃到甜苹果，一定会很开心。", "An'an placed her own apple drawing beside the basket. She imagined how happy she would feel eating a sweet apple tomorrow.", "An'an sets a plain paper bearing a simple drawing of one red apple beside kitchen basket, hopeful smile, no writing, only child and Mom."),
        (4, "又过了一天，那颗红苹果有了一点软。安安把它翻过来看看：“明天，它会变回新鲜的吗？”", "Another day passed, and the red apple softened. An'an turned it over. “Will it become fresh again tomorrow?”", "Close kitchen tabletop: An'an gently examines wrinkled red apple without tasting, Mom stands beside her, thoughtful worried expression, no knife."),
        (5, "妈妈没有马上回答。她想起上周的梨，也是一直放着，最后没能好好吃完。", "Mom paused. She remembered last week's pears, saved for so long that they were never properly enjoyed.", "Quiet kitchen medium shot: Mom looks thoughtfully at current wicker apple basket, An'an listens beside her, no imagined flashback or collage, subdued warm light."),
        (6, "安安说：“要是我们先吃好的，少买一点，是不是就不用天天挑烂的？”妈妈慢慢点了点头。", "An'an asked, “If we enjoy the good ones and buy fewer, would we stop picking through bad ones every day?” Mom nodded slowly.", "Eye-level kitchen conversation: An'an proposes idea with small open-hand gesture, Mom nods with realization, fresh fruit separated clearly from discard bowl."),
        (7, "她们把新鲜苹果放到眼前。安安数了数：“今天我们吃一些，还有一些可以分享。”", "They put the fresh apples where they could see them. An'an counted. “We can eat some today and share some too.”", "Kitchen tabletop overhead: An'an and Mom divide shiny fresh apples between a small plate and small paper gift bag, no spoiled fruit, no labels."),
        (8, "回到家，妈妈说：“省下来的，不只是苹果，也有少一点担心。”安安把空篮子收好，心里轻轻的。", "Back home, Mom said, “We're saving more than apples. We're saving some worry too.” An'an put away the empty basket and felt lighter.", "Warm kitchen medium scene: An'an stores empty wicker basket on a low safe shelf while Mom smiles nearby, small fresh-apple plate on oak table."),
    ],
    "she-bu-de-chuan-de-xin-xie": [
        (2, "安安把鞋带摆得整整齐齐，还在鞋盒下面垫了一张软纸。妈妈说：“你真的很喜欢它们。”", "An'an neatly arranged the laces and put soft paper in the box. Mom said, “You really love these shoes.”", "Entry bench close scene: An'an in socks carefully arranges white-red sneakers inside plain shoebox with tissue, Mom appreciates beside her."),
        (3, "旧鞋踩过草地，也走过小水坑。回家时，安安把旧鞋放在门口，新鞋仍然干干净净地待在盒里。", "Her old shoes crossed grass and little puddles. Back home, she left them by the door. The new pair stayed perfectly clean in its box.", "Entryway: An'an removes faded gray shoes with a few dirt marks onto mat, pristine white-red new shoes visible inside opened box on bench, Mom nearby."),
        (5, "她试着松开鞋带，再把脚伸进去。还是太紧了。妈妈说：“不舒服就不穿，我们先脱下来。”", "She loosened the laces and tried again. Still too tight. Mom said, “You don't have to wear shoes that hurt. Let's take them off.”", "Entry bench: Mom gently helps An'an remove too-small white-red sneaker, child relieved, other shoe already off, no painful injury."),
        (8, "送鞋前，安安摸摸红色鞋边：“希望它们能陪你出去玩。”表妹认真点头，把鞋穿得稳稳的。", "Before giving them away, An'an touched the red trim. “I hope they can go on adventures with you.” Her cousin nodded and put them on securely.", "Living room: An'an in gray old sneakers gives white-red shoes to younger cousin with pigtails pink dress, Mom accompanies, clear affectionate transfer."),
    ],
    "te-bie-de-ri-zi-shi-na-tian": [
        (2, "妈妈问：“你觉得什么日子算特别？”安安想了想：“生日，过年，还有很大很大的好事。”", "Mom asked, “What makes a day special?” An'an thought. “Birthdays, New Year, and really big happy things.”", "Bedroom desk conversation: An'an considers question beside closed sticker box, Mom listens, no birthday montage or writing."),
        (4, "奶奶坐下来，听安安讲学校里的事。她没有带大礼物，却记得安安昨天搭好了一个小桥。", "Grandma sat down to hear about school. She had no big present, but she remembered the little bridge An'an had built yesterday.", "Living room sofa: Grandma attentively listens to animated An'an describing her day, small toy bridge visible on table, Mom nearby, oranges in bowl."),
        (6, "安安先把卡片折好，画了两个人手牵手。她画得有点歪，却越画越想笑。", "An'an folded the card and drew two people holding hands. The drawing was a little crooked, but it made her smile.", "Overhead desk crafting shot: child's drawing of two human stick figures holding hands on blank folded card, crayons nearby, An'an and Mom seated together, no text."),
        (8, "她们一起剥橘子，奶奶听安安讲那颗歪太阳。安安忽然觉得，今天已经有很多可以记住的小事。", "They peeled oranges together while An'an told Grandma about the crooked sun. Suddenly, the day had many little things worth remembering.", "Living room table: An'an and Grandma peel oranges together, handmade card with crooked sun star flower visible, Mom shares quiet happy afternoon."),
    ],
    "wan-ju-shan-li-zhao-xiao-che": [
        (2, "她记得上次玩完，小车停在一座积木桥旁。可是今天，连那座桥也被盒子挡住了。", "Last time, the car had stopped beside a block bridge. Today even the bridge was hidden behind boxes.", "Living room floor: An'an looks behind tall toy bin toward partially hidden wooden bridge, red car absent, no new characters."),
        (4, "安安抱住一只旧布偶：“这个我虽然不常玩，可是还想留着。”爸爸说：“好，它也可以有自己的位置。”", "An'an held an old soft toy. “I don't play with this much, but I still want to keep it.” Dad said, “Of course. It can have a place too.”", "Eye-level floor scene: An'an hugs ordinary inanimate plush keepsake, Dad kneels beside her acknowledging choice, organized bins in progress."),
        (6, "小车找到了，公路却还铺不开。安安看看地板：“原来，我还需要一块可以玩的地方。”", "She had found the car, but there was no room for the road. An'an looked at the floor. “I need a place to play too.”", "Wide living room: An'an holds red toy car while looking at floor blocked by bins, Dad helps think, toy bridge on small clear area."),
        (8, "收好以后，安安试着拿出积木，再放回去。盒子没有装得太满，她自己就能完成。", "After tidying, An'an tried taking out her blocks and putting them back. The box was not too full, so she could do it herself.", "Close low shelf: An'an independently takes a few wooden blocks from manageable open basket, red car parked in its own adjacent spot, Dad watches supportively."),
    ],
    "zai-wan-wu-fen-zhong": [
        (3, "安安觉得，添花园只要一下下。妈妈提醒她：“你还要穿鞋、拿水壶，走到公园也要一会儿。”", "An'an thought adding a garden would be quick. Mom reminded her, “You still need shoes, water, and time to walk to the park.”", "Play table: An'an adds green blocks beside house while Mom points to ready backpack and water bottle near entry, child absorbed, no numbers."),
        (5, "安安低头踢踢地上的小石子：“他会不会不想和我玩了？”妈妈说：“我们可以告诉他发生了什么，也听听他的感受。”", "An'an nudged a tiny stone. “Will he still want to play with me?” Mom said, “We can explain what happened and listen to how he felt.”", "Safe park bench: An'an seated looks down at small pebble by her shoe, Mom listens empathetically, empty slide behind."),
        (7, "乐乐说：“我等了一会儿，以为你忘了。”安安认真听完，和他重新约了一个时间。", "Lele said, “I waited for a while and thought you'd forgotten.” An'an listened, and they made a new plan.", "Home living room: An'an and Mom talk via plain phone on speaker, An'an listening thoughtfully, blank screen no call text, block house in background."),
        (8, "这一次，屋顶还差一块，沙漏就漏完了。安安有点着急。妈妈帮她拍好照片：“回来的时候，还能从这里接着搭。”", "This time, the timer finished before the roof did. An'an felt reluctant. Mom photographed it. “You can carry on right here when we get back.”", "Play table: completed sand timer beside unfinished block roof, Mom photographs house with plain phone, An'an begins stepping away, no screen text."),
    ],
    "wo-de-bing-gan-zen-me-geng-xiao": [
        (2, "她把两只盘子排在眼前，心里越比越不舒服。饼干还是那块饼干，她却一点也不想尝。", "She lined up the plates and compared them. The more she looked, the worse she felt. Her cookie had not changed, but she no longer wanted to taste it.", "Detailed snack tabletop: separate bear-cookie and larger round-cookie plates aligned, An'an compares sizes unhappily, Lele seated opposite, Mom nearby."),
        (4, "妈妈没有说她不知足，只是陪她坐了一会儿。安安说：“我也想吃到够多的。”妈妈记住了这句话。", "Mom did not call her ungrateful. She sat with her. “I want enough to eat too,” An'an said. Mom listened.", "Warm close table scene: Mom sits at An'an's level listening to child's concern, bear cookie remains untouched on own plate, Lele quietly nearby."),
        (6, "乐乐咬了一口自己的圆饼干：“我的中间软一点。”安安说：“我的耳朵脆一点。”他们开始聊起味道。", "Lele tasted his round cookie. “Mine is softer in the middle.” An'an said, “Mine has crunchy ears.” They began talking about flavors.", "Children at snack table discussing cookies happily: Lele holds round cookie with small bite, An'an holds bear cookie with one missing ear, plates separate, no text."),
        (8, "安安把自己的感受说清楚以后，心里松快了。她不用假装不饿，也不用靠抢别人盘里的来解决。", "After An'an explained how she felt, she relaxed. She did not have to pretend she was full or take food from someone else's plate.", "Calm closing snack-table scene before leaving: An'an contentedly chooses one extra snack from communal plate offered by Mom, Lele relaxed, own plates distinct."),
    ],
    "yi-bei-da-fan-de-niu-nai": [
        (2, "蓝色笔滚到一边，安安的手停在半空。她很想让杯子自己站起来，让桌子变回刚才的样子。", "The blue crayon rolled away. An'an's hand froze in the air. She wished the cup could stand up by itself and the table could go back to how it was.", "Close drawing desk: blue crayon rolled safely to desk edge, An'an frozen hand above small milk spill, tipped intact plastic cup, no glass."),
        (4, "湿纸粘住了手指。安安越想快点遮住，越不知道该怎么办。她听见妈妈的脚步，心跳得更快了。", "Wet paper stuck to her fingers. The harder she tried to hide the spill, the less she knew what to do. Mom's footsteps made her heart race.", "Child eye-level desk shot: An'an lifts damp paper stuck lightly to fingertips, worried face, Mom entering background calmly, contained milk puddle."),
        (6, "妈妈问：“有没有碰疼？杯子有没有破？”安安摇头。妈妈说：“好，人没受伤，我们就慢慢处理。”", "Mom asked, “Did you get hurt? Did the cup break?” An'an shook her head. “Good. You're safe, so we can handle this step by step.”", "Mom checks An'an gently beside drawing desk and examines intact plastic cup, child calms, no injuries or broken glass."),
        (8, "擦干净后，安安看看那张画：“它和原来不一样了。”妈妈说：“是呀。有些东西能补，有些会留下痕迹，我们再想想。”", "After cleaning, An'an looked at her drawing. “It's different now.” Mom said, “Yes. Some things can be repaired, and some leave a mark. Let's think about what to do.”", "Quiet desk conversation: An'an and Mom look at dried smudged rainbow drawing laid flat, clear dry surface and cup safely on side table, no fresh spill."),
    ],
    "deng-wo-xin-qing-hao-le-zai-shuo": [
        (2, "安安本来想搭得更快，却让乐乐忙了半天的桥倒下了。她听见积木落在桌上的声音，也看见乐乐的脸变了。", "An'an had wanted to build faster, but she knocked down the bridge Lele had worked hard on. She heard the falling blocks and saw his face change.", "Close play-table: fallen wooden blocks, An'an realizes impact with surprised regret, Lele visibly disappointed, no repeated taking action."),
        (4, "妈妈问她要不要先喝口水。安安慢慢不那么生气了，可是想到开口，肚子还是像打了个小结。", "Mom offered her some water. An'an slowly felt less angry, but the thought of speaking still made her stomach feel knotted.", "Home sofa: An'an drinks water from plain cup to settle, Mom sits quietly beside her, child's expression nervous reflective, no literal stomach graphic."),
        (6, "安安问：“他说不想马上和好怎么办？”妈妈说：“他可以需要时间。你先把自己的话说清楚，不用替他决定。”", "An'an asked, “What if he doesn't want to make up right away?” Mom replied, “He may need time. You can say what you mean without deciding for him.”", "Warm home conversation: Mom and An'an seated eye-to-eye, mother explains patiently, child listens with serious hopeful expression, no friend in scene."),
        (8, "乐乐说，桥倒的时候他很难过。安安没有抢着解释，只点点头：“我听见了。我们可以重新搭，也可以晚一点。”", "Lele said he had felt sad when the bridge fell. An'an listened without rushing to explain. “I hear you. We can rebuild now, or later.”", "Playroom: Lele explains feelings across low block table, An'an listens attentively with hands resting, Mom gives space in background, calm sincere interaction."),
    ],
    "zen-me-zhi-you-wo-zai-shou-shi": [
        (3, "安安说：“刚搭好就要收，真的不想动。”妈妈帮她拍下作品：“想留住它的样子，我们也可以想办法。”", "An'an said, “I just finished it, and now I don't want to put it away.” Mom photographed her work. “We can find a way to keep the memory.”", "Living room block table: Mom photographs An'an's completed block building with plain phone, child appreciates preservation, empty storage bin beside, no visible text."),
        (5, "安安摸摸一只干毛巾，才发现晾衣服也要花时间。爸爸说：“这些事天天都有，不过我们可以一起分着做。”", "An'an touched a dry towel and realized laundry took time too. Dad said, “These jobs come every day, but we can share them.”", "Safe enclosed balcony: An'an touches dry towel on low indoor rack while Dad talks beside her, closed protective window, no outdoor ledge."),
        (7, "爸爸说，他有时也会累。奶奶说，可以把不急的事留到明天。安安听见，大人也需要歇一歇。", "Dad said he sometimes felt tired too. Grandma said some jobs could wait until tomorrow. An'an realized adults needed rest as well.", "Family planning table: Dad speaks honestly, Grandma nods, Mom and An'an listen, job pictogram paper lies between them, relaxed family discussion."),
        (8, "他们约好：一个人忙不过来，可以说需要帮忙；分工不合适，也可以再改。安安觉得这张小图不是命令，而是商量。", "They agreed that anyone could ask for help, and the plan could change if it did not work. To An'an, the little picture was an agreement, not an order.", "Close family dining table: An'an points to hand-drawn job pictograms while family discusses together, supportive expressions, no writing or printed chart."),
    ],
    "bu-tai-wan-mei-de-ye-can": [
        (2, "安安给餐盒留了一个位置，又挑了最喜欢的水壶。她已经想好，要坐在大树下，边吃边看云。", "An'an made space for the lunchbox and chose her favorite water bottle. She imagined eating beneath a big tree and watching clouds.", "Home kitchen: An'an arranges plain lunchbox and favorite water bottle in picnic basket, Mom beside her holds folded blanket, sunny window, no imagination bubble."),
        (4, "亭子里干干的，外面的草地却湿了。爸爸先确认没有雷声，也没有积水，再把毯子和食物放好。", "The pavilion was dry, but the grass outside was wet. Dad checked that there was no thunder or flooding before setting out the blanket and food.", "Safe dry park pavilion wide scene: Dad surveys gentle rain outside and lays dry blanket on bench, Mom and An'an seated protected, no lightning or flooding."),
        (6, "妈妈问：“你想先安静一会儿，还是吃点东西？”安安想了想：“先听听雨吧。”大家就陪她坐了一会儿。", "Mom asked, “Would you like a quiet moment or something to eat?” An'an thought. “Let's listen to the rain first.” The family sat with her.", "Peaceful pavilion bench: An'an Mom Dad sit quietly together looking at gentle rain beyond shelter, picnic basket closed nearby, empathetic calm mood."),
        (8, "爸爸问：“还想在这里待一会儿吗？也可以回家。”安安看看雨后亮亮的树叶：“我想再走一小段。”", "Dad asked, “Would you like to stay a little longer? We can go home too.” An'an looked at the shiny wet leaves. “I'd like a short walk.”", "Pavilion edge after rain eases: Dad asks An'an, she points toward safe dry pedestrian path with sparkling wet leaves, Mom holds her hand, no storm."),
    ],
}

def expanded_pages(slug, pages):
    result = []
    for page_index, page in enumerate(pages, 1):
        for before, zh, en, prompt in EXTRA_PAGES[slug]:
            if before == page_index:
                result.append((zh, en, prompt))
        result.append(page)
    return result

def main():
    out = ROOT / "content-drafts/richang"
    out.mkdir(parents=True, exist_ok=True)
    for order, (slug, title, subtitle, moral, moral_en, tags, pages, goal, reminder, questions, activity) in enumerate(BOOKS, 1):
        pages = expanded_pages(slug, pages)
        book = {
            "id": slug, "seriesId": "richang", "title": title, "subtitle": subtitle,
            "moral": {"zh": moral, "en": moral_en},
            "ageLabel": "4–8 岁", "publishedAt": "2026-10-01", "order": order,
            "comingSoon": True,
            "pages": [{"page": i, "zhText": zh, "enText": en, "illustrationPrompt": prompt} for i, (zh, en, prompt) in enumerate(pages, 1)],
            "metadata": {"category": "family-growth", "ageRange": {"min": 4, "max": 8}, "estimatedMinutes": 5, "languages": ["zh", "en"], "seriesId": "richang", "seriesOrder": order, "personalizationEnabled": False, "tags": ["日常系列", "生活智慧", "亲子共读", *tags], "featured": order <= 3, "bedtimeSuitable": True},
            "parentGuide": {"goal": goal, "reminder": reminder, "questions": questions, "activity": activity, "ageTips": {"age4to5": "先看表情和动作，说一说主人公的感受，再选一个小行动试试。", "age6to8": "讨论选择的原因和结果，也允许提出不同办法；联系自己经历过的一件小事。"}},
        }
        file = out / f"{slug}.json"
        if file.exists():
            existing = json.loads(file.read_text())
            if existing["book"].get("comingSoon") is not True or any(p.get("imageStatus") == "complete" for p in existing["book"]["pages"]):
                raise RuntimeError(f"Refusing to overwrite a completed book: {file}")
        file.write_text(json.dumps({"book": book, "imagePromptKit": {"globalStyle": STYLE, "characterConsistency": CHARACTERS, "negative": NEGATIVE}}, ensure_ascii=False, indent=2) + "\n")
    manifest = out / "local-audio.json"
    if not manifest.exists():
        manifest.write_text("{}\n")
    print(f"Created {len(BOOKS)} books, {sum(len(expanded_pages(b[0], b[6])) for b in BOOKS)} bilingual pages")

if __name__ == "__main__":
    main()
